# If you come from bash you might have to change your $PATH.
export MPLBACKEND="MacOSX"
# export PATH="$PATH:/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin"
export PATH="/usr/local/opt/ruby/bin:$PATH"
export PATH="$PATH:/usr/local/lib/ruby/gems/3.0.0/bin"
export GOPATH="$HOME/.go"
export PATH="/Users/kai/.local/bin:$PATH"

export EDITOR=nvim

# source colorls tab completion 
source $(dirname $(gem which colorls))/tab_complete.sh


pdfcompress ()
{
  if ! zparseopts -E -D -F -- c=copyflag -copy=copyflag h=help -help=help; then
    return -1
  fi
  if [[ ! -z $help ]]; then
    echo "Takes a bunch files as positional parameters. You can pass the -c flag to copy with new filename or --help/-h to show this text."
    return 0
  fi
  for i in "$@"; do
    outfile="$i".compressed.pdf
    printf "compressing $i  to $outfile\n"
    gs -q -dNOPAUSE -dBATCH -dSAFER -sDEVICE=pdfwrite -dCompatibilityLevel=1.3 -dPDFSETTINGS=/screen -dEmbedAllFonts=true -dSubsetFonts=true -dColorImageDownsampleType=/Bicubic -dColorImageResolution=144 -dGrayImageDownsampleType=/Bicubic -dGrayImageResolution=144 -dMonoImageDownsampleType=/Bicubic -dMonoImageResolution=144 -sOutputFile=$outfile "$i"; 
    if [[ ! -z $copyflag ]]; then
      printf "."
    else
      printf "overriding original $i\n"
      mv "$i".compressed.pdf "$i"
    fi
  done
}


printmany ()
{
  if ! zparseopts -E -D -F -- h=help -help=help; then
    return -1
  fi
  if [[ ! -z $help ]]; then
    echo "Takes a bunch files as positional parameters and sends them for printing to the NUC. Add --help/-h to show this text."
    return 0
  fi
  for i in "$@"; do
    printf "printing $i \n"
    scp "$i"  192.168.0.2:to_print.pdf ; ssh 192.168.0.2 'lp -o fit-to-page ~/to_print.pdf'
    sleep 3
  done
}



mergepdfs () { 
  if ! zparseopts -E -D -F -- h=help -help=help; then
    return -1
  fi
  if [[ ! -z $help ]]; then
    echo "Merges a bucnh of pdf files into one. Example: 'mergepdfs a.pdf b.pdf c.pdf' turns a.pdf and b.pdf into c.pdf. Add --help/-h to show this text."
    return 0
  fi
  gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile="$1" "${@:2}"
}


changes(){
  for dir in $HOME/Development/*/     # list directories absolute path
  do
      if [[ -d "$dir/.git" ]]; then
          if [[ -n  `git -C $dir status --porcelain` ]]; then
              echo "Uncommited changes in directory:  $dir"
              continue;
          fi
          if [[ -n `git -C $dir log --branches --not --remotes` ]]; then
              echo "Unpushed changes in directory: $dir "
          fi
      fi
  done
}


listenv(){
 ls  "$HOME/.envs"
}


rmenv(){
  if [ -z "$1" ]; then
    echo "No name for venv supplied"
    return 1
  fi
  echo "Remove environment at $HOME/.envs/$1 (y/n) ? "
  read answer
  if [ "$answer" != "${answer#[Yy]}" ] ;then
    echo rm -r $HOME/.envs/$1
  else
    echo No
  fi
}


mkenv(){
 if [ -z "$1" ]; then
   echo "No name for venv supplied"
   return 1
 fi
 mkdir -p "$HOME/.envs"
 python3 -m venv "$HOME/.envs/$1"
 echo "Venv created at $HOME/.envs/$1"
 activate $1
 pip install ipython jupyter
 deactivate
}


activate(){
 if [ -z "$1" ]; then
   echo "No name for venv supplied"
   return 1
 fi
 if [ ! -d "$HOME/.envs/$1" ]; then
   echo "No venv with that name"
   return 1
 fi
 source "$HOME/.envs/$1/bin/activate"
}

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"



# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="spaceship"


export SPACESHIP_GIT_STATUS_ADDED="%F{yellow}+%F{red}"
export SPACESHIP_GIT_STATUS_UNTRACKED="%F{blue}?%F{red}"
export SPACESHIP_GIT_STATUS_DELETED="%F{green}x%F{red}"
export SPACESHIP_GIT_STATUS_MODIFIED="%F{yellow}!%F{yellow}"
export SPACESHIP_GIT_STATUS_PREFIX=" "
export SPACESHIP_GIT_STATUS_SUFFIX=" "
export SPACESHIP_TIME_SHOW=true
export SPACESHIP_BATTERY_THRESHOLD=100

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)
plugins=(virtualenv)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"


alias gits="git status"
alias commit="git commit"
alias add="git add"
alias push="git push"
alias pull="git pull"
alias vim="nvim"
alias vimdiff="nvim -d"
alias ls="colorls --sd"
alias lsa="colorls -A --sd"
alias ll="colorls -l --sd"
alias lla="colorls -lA --sd"
alias code="open -b com.microsoft.VSCode"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

